src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="task")
 */
class Task
{
    const NUM_ITEMS = 10;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * Название задачи
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @var string
     *
     * Описание задачи
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @var string
     *
     * Заготовка для решения задачи
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $template;

    /**
     * @var string
     *
     * Тесты
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $test;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     */
    private $createdAt;


    /**
     * @ORM\OneToMany(targetEntity="Solve", mappedBy="task")
     */
    private $solves;


    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->solves = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle(string $title)
    {
        $this->title = $title;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription(string $description)
    {
        $this->description = $description;
    }

    /**
     * @return string
     */
    public function getTemplate()
    {
        return $this->template;
    }

    /**
     * @param string $template
     */
    public function setTemplate(string $template)
    {
        $this->template = $template;
    }

    /**
     * @return string
     */
    public function getTest()
    {
        return $this->test;
    }

    /**
     * @param string $test
     */
    public function setTest($test)
    {
        $this->test = $test;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return mixed
     */
    public function getSolves()
    {
        return $this->solves;
    }

    //
    /**
     * @return float
     */
    public function getPercents()
    {
        $arr = $this->getSolves()->toArray();
        $solved = count(array_filter($arr, function ($solve) {
            /** @var $solve Solve */
            return $solve->getStatus() == Solve::STATUS_SOLVED;
        }));
        
        return round($solved / count($arr) * 100, 2);
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, ['attr' => ['class' => 'form-control']])
            ->add('description', TextareaType::class, ['attr' => ['class' => 'form-control']])
            ->add('template', TextareaType::class, ['attr' => ['class' => 'form-control']])
            ->add('test', TextareaType::class, ['attr' => ['class' => 'form-control']])
            ->add('save', SubmitType::class, ['attr' => ['class' => 'btn btn-primary'], 'label' => 'Добавить задачу']);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Task::class,
        ));
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Solve;
use App\Entity\Task;
use App\Form\SolveType;
use App\Form\TaskType;
use App\Service\SolveMaker;
use App\Service\TaskMaker;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class TaskController
 *
 * @Route("/tasks")
 *
 * @package App\Controller
 */
class TaskController extends Controller
{
    private $taskMaker;
    private $solveMaker;

    /**
     * TaskController constructor.
     * @param TaskMaker $taskMaker
     * @param SolveMaker $solveMaker
     */
    public function __construct(
        TaskMaker $taskMaker,
        SolveMaker $solveMaker
    )
    {
        $this->taskMaker = $taskMaker;
        $this->solveMaker = $solveMaker;
    }

    /**
     * @Route("/", defaults={"page": "1", "_format"="html"}, name="task_index")
     * @Method("GET")
     *
     * @param $_format
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction($_format = 'html')
    {
        $tasks = $this->getDoctrine()->getRepository(Task::class)->findAll();
        return $this->render('task/index.' . $_format . '.twig', ['tasks' => $tasks]);
    }

    /**
     * @Route("/view/{id}", name="task_view")
     * @Method("GET")
     *
     * @param Task $task
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function viewAction(Task $task)
    {
        $solve = new Solve();
        $solve->setCode($task->getTemplate());

        $form = $this->createForm(SolveType::class, $solve, [
            'action' => $this->generateUrl('task_solve', ['id' => $task->getId()]),
            'method' => 'POST',
        ]);
        return $this->render('task/view.html.twig', [
            'task' => $task,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/add", name="task_add")
     * @Method({"GET", "POST"})
     *
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function addAction(Request $request)
    {
        $task = new Task();

        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $task = $this->taskMaker->add($form->getData());
            return $this->redirectToRoute('task_view', ['id' => $task->getId()]);
        }

        return $this->render('task/add.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/solve/{id}", name="task_solve")
     * @Method("POST")
     *
     * @param Task $task
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function solveAction(Task $task, Request $request)
    {
        $solve = new Solve();
        
        $form = $this->createForm(SolveType::class, $solve);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $result = $this->solveMaker->add($task, $form->getData());
            return $this->json([
                'status' => $result['status'],
                'output' => $result['output']
            ]);
        }
        return $this->json([
            'status' => Solve::STATUS_UNSOLVED,
            'output' => ['FAILURES!']
        ]);
    }
}

templates/task/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Добавить задачу / Задачи
{% endblock %}

{% block body %}
    <h1>Добавить задачу</h1>

    {{ form_start(form) }}

    {{ form_errors(form) }}

    <div class="form-group">
        {{ form_label(form.title, 'Название задачи') }}
        {{ form_errors(form.title) }}
        {{ form_widget(form.title) }}
    </div>

    <div class="form-group">
        {{ form_label(form.description, 'Постановка задачи') }}
        {{ form_errors(form.description) }}
        {{ form_widget(form.description) }}
    </div>

    <div class="form-group">
        {{ form_label(form.template, 'Начало задачи') }}
        {{ form_errors(form.template) }}
        <div>
            <kbd>&lt;?php</kbd>
            {{ form_widget(form.template) }}
            <kbd>?&gt;</kbd>
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.test, 'Тесты') }}
        {{ form_errors(form.test) }}
        <div>
            <kbd>&lt;?php</kbd><br/>
            <kbd>declare(strict_types=1);</kbd><br/><br/>
            <kbd>use PHPUnit\Framework\TestCase;</kbd><br/><br/>
            <kbd>class TaskTest extends TestCase</kbd><br/>
            <kbd>{</kbd><br/>
            {{ form_widget(form.test) }}
            <kbd>}</kbd>
        </div>

    </div>

    {{ form_end(form) }}
{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Задачи
{% endblock %}

{% block body %}
    <div class="jumbotron">
        <h1 class="display-3">Работай головой</h1>
        <p class="lead">Решай задачи, прокачивай свои навыки, зарабытывай очки опыта и обменивай их на полезный стаф!</p>
        <p><a class="btn btn-lg btn-success" href="#" role="button">Регистрируйся сегодня!</a></p>
    </div>

    <div class="row marketing">

        <div class="col-lg-12">
            <h2>Задачи</h2>
            {% for task in tasks %}
                <h4>
                    <a href="{{ path('task_view', {id: task.id}) }}">
                        {{ task.title }}
                    </a>
                </h4>
                <p>{{ task.description|striptags }}</p>
                <span class="label label-success" data-toggle="tooltip" data-placement="top" title="Успешных решений">{{ task.percents }}%</span>
                <span class="label label-primary" data-toggle="tooltip" data-placement="top" title="Уровень сложности">Легко</span>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/task/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ task.title|striptags }} / Задачи
{% endblock %}


{% block body %}
    <h1>{{ task.title }}</h1>
    <p class="lead">{{ task.description|raw }}</p>

    {{ form_start(form) }}

    {{ form_errors(form) }}
        <div class="form-group">
            {{ form_label(form.code, 'Ваше решение') }}
            <div>
                <kbd>&lt;?php</kbd>
                {{ form_widget(form.code) }}
                <kbd>?&gt;</kbd>
            </div>
        </div>
        <pre id="output" style="display: none"></pre>
        <p id="result"></p>
    {{ form_end(form) }}
{% endblock %}